spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml
    url: jdbc:h2:mem:products;DB_CLOSE_DELAY=-1;
    user: sa
    password: sa
    contexts: data,schema
  test:
    database:
      replace: none
  logging:
    level:
      liquibase: DEBUG
  r2dbc:
    url: r2dbc:h2:mem:///products
    username: sa
    password: sa
  h2:
    console:
      enabled: false
logging:
  level:
    root: INFO
